def error_handling():
    try:
        print('try except block')
    except ValueError:
        print('Value error happened!')